title: Genesys Web Messenger Tester
description: Example desc
theme: just-the-docs

url: https://genesys-messenger-tester.makingchatbots.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
