title: Genesys Web Messenger Tester
description: Free and open-source tool for automatically testing your Genesys Web Messenger Deployments
theme: just-the-docs

url: https://genesys-messenger-tester.makingchatbots.com

footer_content: "Copyright &copy; 2023 Lucas Woodward"

author: Lucas Woodward
social:
  name: Lucas Woodward
  links:
    - https://www.linkedin.com/in/lucas-woodward-the-dev
    -
nav_external_links:
  - title: GitHub Project
    url: https://github.com/ovotech/genesys-web-messaging-tester
    hide_icon: false
    opens_in_new_tab: true