title: Genesys Web Messenger Tester
description: Free and open-source tool for automatically testing your Genesys Web Messenger Deployments
theme: just-the-docs

url: https://genesys-messenger-tester.makingchatbots.com

aux_links:
  GitHub: https://github.com/ovotech/genesys-web-messaging-tester

footer_content: "Copyright &copy; 2023 Lucas Woodward"

author: Lucas Woodward
social:
  name: Lucas Woodward
  links:
    - https://www.linkedin.com/in/lucas-woodward-the-dev
